In [1]:
#slicing
name='sathish'
name[0:4]

'sath'

In [2]:
name[2:]

'thish'

In [5]:
name[:5:2]

'sti'

In [6]:
name[-1]

'h'

In [11]:
name[-4:-1]

'his'

In [19]:
name[::-1]

'hsihtas'

In [18]:
name[-5:3]

't'

In [20]:
name[2:-1]

'this'

In [22]:
name[-3:-1]

'is'

In [25]:
name[-4:-3]

'h'

In [27]:
#numpy(numerical python)
#collect the data-->preprocess
#store the data in n dimensions
#1d,2d,3d,4d
heros=['srk','kalyan','vijay']
pairs=[['srk','deepika'],
      ['ntr','alia']
]
print(heros,pairs)

['srk', 'kalyan', 'vijay'] [['srk', 'deepika'], ['ntr', 'alia']]


In [29]:
print(heros[0],pairs[0][1])

srk deepika


In [2]:
import numpy as np
nums=np.array([1,2,3])

In [3]:
nums.shape

(3,)

In [4]:
nums.size #every element is size

3

In [42]:
np.sum(nums)

6

In [40]:
len(nums)

3

In [39]:
def display(name,age):
    print(f'my name is {name} and age is {age}')
display('sandhya',32)

my name is sandhya and age is 32


In [40]:
#2d
num=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


In [41]:
print(num)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
num[2][0]

7

In [46]:
num[-2]

array([4, 5, 6])

In [47]:
num[1][-2]

5

In [43]:
print(type(num))

<class 'numpy.ndarray'>


In [26]:
num.shape

(3, 3)

In [27]:
len(num)

3

In [28]:
num.size

9

In [29]:
num.itemsize

4

In [49]:
#3d
nums=np.array([
        [
            [1,2,3],
        ],
    [
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
])

In [51]:
nums[2][0][2]

9

In [ ]:
nums[]

In [31]:
nums

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [32]:
nums.shape

(3, 1, 3)

In [33]:
nums.ndim

3

In [34]:
len(nums)

3

In [35]:
len(nums[0])

1

In [53]:
#zeros
nums=np.zeros((3,4),dtype=int)
nums

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
nums=np.ones((3,4),dtype=int)
nums

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [55]:
nums=np.full((3,4),20)
nums

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [56]:
nums=np.identity(3)
nums

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
nums=np.array([1,2,3],ndmin=2)
nums

array([[1, 2, 3]])

In [62]:
nums=np.array([3,4,5])
nums+4

array([7, 8, 9])