In [1]:
#1. Create a numpy array with numpy.array module and with a data type integer and float.
import numpy as np
array1=np.array([20,30,40,50])
array2=np.array([12.5,15.6,1.5])

In [4]:
print(array1)
print(array2)


[20 30 40 50]
[12.5 15.6  1.5]


In [21]:
#2.Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
#Also, print the shape and dimensions of the numpy arrays created above

In [25]:
arr=np.array([1,2,3])#1d
arr.shape
arr.ndim

1

In [26]:
arr=np.array([[[1,2,3]]]) #3d
arr.shape
arr.ndim

3

In [16]:
a=np.random.randint(1,50,size=(4,4))
a

array([[ 1,  2, 18, 37],
       [ 8, 23, 43, 13],
       [19, 33,  8, 18],
       [33, 23, 24,  1]])

In [7]:
a.shape

(4, 4)

In [20]:
a.ndim

2

In [29]:
#ways to create an array
np.arange(0,100,25)

array([ 0, 25, 50, 75])

In [31]:
#range(0,10)--it return sequence of values
np.array(range(0,10,2))

array([0, 2, 4, 6, 8])

In [27]:
#3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.
b=np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
b=np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
#4. Create a numpy array with shape 2x5 that has all the elements as zero.
a=np.zeros((2,5),dtype=int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [46]:
#5. Create a numpy array that has the shape 3x5 and all the elements are 5.
a=np.full((3,5),5)
a

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [50]:
a=np.ones((3,5),dtype=int)
a*5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
#6. Create a numpy array with random integers in the range 0-100, 
#and the sample sizeshould be 25.

In [53]:
a=np.random.randint(0,100,25)
a

array([94, 83, 56, 24, 45, 36, 33, 96, 86, 76, 66, 95, 22, 56, 48, 75, 33,
       16, 23, 71, 61, 65, 68, 56, 32])

In [55]:
#7. Create a numpy array with a shape 3x3 that has all elements as 1
a=np.full((3,3),1)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
#Reshape the array in the shape 3x2 and print the updated shape of the resultant array.


In [60]:
a=np.random.randint(0,100,size=(2,3))
a

array([[ 2, 14, 69],
       [14, 95, 74]])

In [63]:
b=a.reshape(3,2)
b

array([[ 2, 14],
       [69, 14],
       [95, 74]])

In [ ]:
#9. Create a random array, with the range 0-1000, with a size 50 and 
#step 2. Perform the following operations on the same.
#a. Print the first ten elements of the array.
#b. Print the last ten elements of the array
#c. Print the elements from the indexes 10-25
#d. Print the element at the index 22
#e. Print the array using negative indexing.
#f. Print the last ten elements of the array, using negative indexing

In [64]:
arr1=np.random.randint(0,1000,50)

In [65]:
arr1

array([527, 256, 609, 711, 549, 708, 195, 395, 286, 189, 151, 745,  67,
       687, 240,  19, 289, 818, 716, 688, 643, 640, 304, 295, 488, 559,
       575,  13, 628, 201, 457, 929, 797, 377, 197, 160, 253,  74, 176,
        89, 405, 154,  88, 146, 245, 873, 708, 832, 810, 468])

In [67]:
arr1[0:10]

array([527, 256, 609, 711, 549, 708, 195, 395, 286, 189])

In [71]:
arr1[-10 :]

array([405, 154,  88, 146, 245, 873, 708, 832, 810, 468])

In [74]:
arr1[10:25]

array([151, 745,  67, 687, 240,  19, 289, 818, 716, 688, 643, 640, 304,
       295, 488])

In [76]:
arr1[22]

304

In [75]:
arr1[::-1]

array([468, 810, 832, 708, 873, 245, 146,  88, 154, 405,  89, 176,  74,
       253, 160, 197, 377, 797, 929, 457, 201, 628,  13, 575, 559, 488,
       295, 304, 640, 643, 688, 716, 818, 289,  19, 240, 687,  67, 745,
       151, 189, 286, 395, 195, 708, 549, 711, 609, 256, 527])

In [78]:
arr1[-10:]

array([405, 154,  88, 146, 245, 873, 708, 832, 810, 468])

In [ ]:
#10. Given a numpy array that has values = [1,2,3,4,5]. 
#Perform the following operations.
#a. Insert the element 6 at the end of the array.
#b. Insert the element 10 at the beginning of the array.
#c. Insert the element 30, before 4.
#d. Update the element 5 as 50.
#e. Delete the element 50 in the updated array.
#f. Create a function to search for the element 30.
#g. Sort the array in ascending order

In [80]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [82]:
arr=np.insert(arr,5,6)
arr

array([1, 2, 3, 4, 5, 6])

In [83]:
arr=np.insert(arr,0,10)
arr

array([10,  1,  2,  3,  4,  5,  6])

In [84]:
arr=np.insert(arr,4,30)
arr

array([10,  1,  2,  3, 30,  4,  5,  6])

In [86]:
arr[6]=50


In [87]:
arr

array([10,  1,  2,  3, 30,  4, 50,  6])

In [88]:
arr=np.delete(arr,6)
arr

array([10,  1,  2,  3, 30,  4,  6])

In [96]:
#f. Create a function to search for the element 30.
def search(num,arr):
    if num in arr:
        print('30 present')
    else:
        print('not found')
    
search(30,arr)

30 present


In [98]:
arr=np.sort(arr)
arr

array([ 1,  2,  3,  4,  6, 10, 30])