In [1]:
import numpy as np


In [13]:
num1=np.array(
    [1,2,3],
     [4,5,6])

num2=np.repeat(num1,3,axis=0)
print(num2)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [10]:
print(num2)

[1 1 1 2 2 2 3 3 3]


In [14]:
#list vs numpy
list1=[10,20,'vasi']
list2=list1
print(list1,list2)
list1[0]=50
print(list1,list2)

[10, 20, 'vasi'] [10, 20, 'vasi']
[50, 20, 'vasi'] [50, 20, 'vasi']


In [21]:
#speed test
a=np.random.randint(1,100,size=(3,4))
a

array([[93, 88, 45, 90],
       [43, 94, 43, 38],
       [47, 62, 65, 31]])

In [22]:
a=np.random.uniform(1,100,size=(3,4))
a

array([[69.52866438, 82.86699785, 91.36986234, 66.21126632],
       [16.90250435, 22.69958726, 72.99071501, 41.89263025],
       [56.80469598, 66.98291769, 67.06017436, 84.58591403]])

In [26]:
from timeit import default_timer  as timer
a=np.random.random(500)
b=np.random.random(500)
print(type(a))
l1=list(a)
l2=list(b)
def find_product():
    dot=0
    for i in range(len(l1)):
        dot +=l1[i]*l2[i]
    return dot
def find_dot():
    return np.dot(a,b)

start=timer()
for i in range(1000):
    find_product()
end=timer()
print(end-start)

<class 'numpy.ndarray'>
0.20564269999977114


In [36]:
a1=np.array([10,20,30,40,50])
a1[1::2]

array([20, 40])

In [37]:
a1[0::2]

array([10, 30, 50])

In [39]:
a1[-3:-1]

array([30, 40])

In [40]:
a1[-2:-5]

array([], dtype=int32)

In [42]:
a1[:2:-1]

array([50, 40])

In [45]:
#2d array
nums=np.array([
    [11,12,13,14,15,16,17,18],
    [21,22,23,24,25,26,27,28]
])
nums[0:2]


array([[11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28]])

In [46]:
nums[0:1]

array([[11, 12, 13, 14, 15, 16, 17, 18]])

In [49]:
nums[1:2]

array([[21, 22, 23, 24, 25, 26, 27, 28]])

In [51]:
nums[0][5]

16

In [54]:
nums[-1::-1]

array([[21, 22, 23, 24, 25, 26, 27, 28],
       [11, 12, 13, 14, 15, 16, 17, 18]])

In [55]:
nums[0,1:5]

array([12, 13, 14, 15])

In [59]:
nums[-2,2:-3]

array([13, 14, 15])

In [60]:
nums[1,-7:5:2]

array([22, 24])

In [62]:
nums[-2,4:-4]

array([], dtype=int32)

In [63]:
#multiple rows and multiple columns
print(nums[:])

[[11 12 13 14 15 16 17 18]
 [21 22 23 24 25 26 27 28]]


In [64]:
print(nums[:,2:5])

[[13 14 15]
 [23 24 25]]


In [65]:
#change values using slicing
nums=np.array([
    [11,12,13,14,15,16,17,18],
    [21,22,23,24,25,26,27,28]
])
nums[1,3:5]=20
nums

array([[11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 20, 20, 26, 27, 28]])

In [66]:
nums[1,3]=75

In [67]:
nums

array([[11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 75, 20, 26, 27, 28]])